[16.0][MIG] mis_builder_analytic: Migration to 16.0
OCA/mis-builder-contrib pull request #49
Opened 2024-04-24 09:24 UTC by peluko00

2024-04-24 11:01 UTC, mpascuall approved these changes
Working correctly, checked in runboat

2024-04-24 14:46 UTC, douglascstd requested changes
[FUNCTIONAL REVIEW]

Thank you for migrating this module. It will be useful for everyone. 


The selection by filters does not appear, even with the option selected
![image](https://github.com/OCA/mis-builder-contrib/assets/20867090/d50922d2-3aec-49de-8a6b-cfe36ecaecee)
![image](https://github.com/OCA/mis-builder-contrib/assets/20867090/d000dc83-de97-4736-ae58-a25775b92dd8)



TEST
Bill:
![image](https://github.com/OCA/mis-builder-contrib/assets/20867090/6b9b9252-f198-4630-878f-4491c7df1bc2)

Mis Builder Report:
![image](https://github.com/OCA/mis-builder-contrib/assets/20867090/e0a9a30a-8fc3-4d32-a388-fc42f91a7b10)

Dropdown the value:
![image](https://github.com/OCA/mis-builder-contrib/assets/20867090/92c81c3e-52c8-4d79-9f12-9e4f5a6f0e6d)

Investigation v14 and v16:
![image](https://github.com/OCA/mis-builder-contrib/assets/20867090/6f0ce492-2c30-45a0-a06f-1d1486e6e5a9)
![image](https://github.com/OCA/mis-builder-contrib/assets/20867090/11f9af42-7572-4b23-baf4-8f97d057a6d6)
![image](https://github.com/OCA/mis-builder-contrib/assets/20867090/90e1d9b1-bed6-4fe4-b8ae-b936b3bcbc62)

2024-05-02 09:46 UTC, peluko00 commented
> [FUNCTIONAL REVIEW]
> 
> Thank you for migrating this module. It will be useful for everyone.
> 
> The selection by filters does not appear, even with the option selected ![image](https://private-user-images.githubusercontent.com/20867090/325266648-d50922d2-3aec-49de-8a6b-cfe36ecaecee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDM0NTQsIm5iZiI6MTcxNDY0MzE1NCwicGF0aCI6Ii8yMDg2NzA5MC8zMjUyNjY2NDgtZDUwOTIyZDItM2FlYy00OWRlLThhNmItY2ZlMzZlY2FlY2VlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDA5NDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMjZkOGU1ZDBjY2JmOGUyYWM5MTMxNDEwNWIwMmEwNjQyNTUyOWJmZWM0YmIzNjliODRjODBkODJiOTVhMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RzT34nXhwDroR6YrEwM9FWW5dxN4AS4CI8vm8WggU3c) ![image](https://private-user-images.githubusercontent.com/20867090/325267020-d000dc83-de97-4736-ae58-a25775b92dd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDM0NTQsIm5iZiI6MTcxNDY0MzE1NCwicGF0aCI6Ii8yMDg2NzA5MC8zMjUyNjcwMjAtZDAwMGRjODMtZGU5Ny00NzM2LWFlNTgtYTI1Nzc1YjkyZGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDA5NDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NjQ2ZmVmNjUwYjIyMDc5YjBjYTg2NzVlYjY5OTc5YTJhMmJkNzYyNjkyZWE2ZjZiYWI1ZDBiNTg3NWMxNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IegREAJqT9lBHQBtgRvNMGerTDz73XwfQoXSffjK2HU)
> 
> TEST Bill: ![image](https://private-user-images.githubusercontent.com/20867090/325264260-6b9b9252-f198-4630-878f-4491c7df1bc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDM0NTQsIm5iZiI6MTcxNDY0MzE1NCwicGF0aCI6Ii8yMDg2NzA5MC8zMjUyNjQyNjAtNmI5YjkyNTItZjE5OC00NjMwLTg3OGYtNDQ5MWM3ZGYxYmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDA5NDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZmM0ZDExNDg1ODFkMDBlNWVmYjNhYzNmMjcyMTJjODc3YmJlNDgxMGZiYWIxNjNjMGQ4M2QyMDExZDI2YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MXPLDHSOSS_Hn5NWp1T5JNidOO-kx--lsJ78Bp1bLkE)
> 
> Mis Builder Report: ![image](https://private-user-images.githubusercontent.com/20867090/325264404-e0a9a30a-8fc3-4d32-a388-fc42f91a7b10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDM0NTQsIm5iZiI6MTcxNDY0MzE1NCwicGF0aCI6Ii8yMDg2NzA5MC8zMjUyNjQ0MDQtZTBhOWEzMGEtOGZjMy00ZDMyLWEzODgtZmM0MmY5MWE3YjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDA5NDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMGExNWI5ZTlmMDI1N2Y0MTcyZGI4YjU2ZTZlZTE3ZWI3NGZhNWZkMWFlYjQ5MmFlZDgwODcwNjc3NmQ4MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OoFUUZBw-YZ29ZOyO60TMX7tNk8K9-2K0dYK1SScpks)
> 
> Dropdown the value: ![image](https://private-user-images.githubusercontent.com/20867090/325264562-92c81c3e-52c8-4d79-9f12-9e4f5a6f0e6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDM0NTQsIm5iZiI6MTcxNDY0MzE1NCwicGF0aCI6Ii8yMDg2NzA5MC8zMjUyNjQ1NjItOTJjODFjM2UtNTJjOC00ZDc5LTlmMTItOWU0ZjVhNmYwZTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDA5NDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNzExYjg4ZjQxOTM2YmFhNjFhZjM2YmNhNTEyMDYyMTFiZjc5MzNkYmQ2YmUyMzY2ODBhNWM2ODUzMmUzYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YmixpzSsVh1p4M23qRlAJealvPgwfLyktYLOI4dC4Y8)
> 
> Investigation v14 and v16: ![image](https://private-user-images.githubusercontent.com/20867090/325264734-6f0ce492-2c30-45a0-a06f-1d1486e6e5a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDM0NTQsIm5iZiI6MTcxNDY0MzE1NCwicGF0aCI6Ii8yMDg2NzA5MC8zMjUyNjQ3MzQtNmYwY2U0OTItMmMzMC00NWEwLWEwNmYtMWQxNDg2ZTZlNWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDA5NDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3M2NiMTk0OWY4NjYyY2JlN2NiMDcxZmI0ZTA2ZGFkN2YwNzRhNjQ0YTBhNzg3MTdlNGE5YjNjYjk4NzI4NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fbtPYNuJD50fC6sBMvMAAb6E3NLFGuliwUExnM6JUUM) ![image](https://private-user-images.githubusercontent.com/20867090/325264833-11f9af42-7572-4b23-baf4-8f97d057a6d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDM0NTQsIm5iZiI6MTcxNDY0MzE1NCwicGF0aCI6Ii8yMDg2NzA5MC8zMjUyNjQ4MzMtMTFmOWFmNDItNzU3Mi00YjIzLWJhZjQtOGY5N2QwNTdhNmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDA5NDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNGRiYzIwZDdkZDQ1NzM1NWMxYTBmN2E4ZDJhNThkOGQ2ODI2M2JjYTQyYWUwOWJlMGMxYjgyMGFjMzE4OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bsFf8Cot6lH3dKtc3xD4WYlBHHT3KWaSJIvajgbPbUo) ![image](https://private-user-images.githubusercontent.com/20867090/325265113-90e1d9b1-bed6-4fe4-b8ae-b936b3bcbc62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDM0NTQsIm5iZiI6MTcxNDY0MzE1NCwicGF0aCI6Ii8yMDg2NzA5MC8zMjUyNjUxMTMtOTBlMWQ5YjEtYmVkNi00ZmU0LWI4YWUtYjkzNmIzYmNiYzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDA5NDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMTMwZjEwZDhlNTJiMTMxZjM5OGRjYWY5OTQ4ODk1NWZkMzMzMDIzMGE3M2E3NWE4ODAyZjZkMjU5MzllZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mBCNbuwuGMkoL2Iuoow1_wc8ITow0yxlzCq5Kxgtjaw)

This changes not affected to this module, review again please

2024-08-15 03:32 UTC, hitrosol commented
runboat is not working...

2024-08-15 06:36 UTC, peluko00 commented
> runboat is not working...

Done!

2024-08-15 09:21 UTC, hitrosol commented
Thanks for this migration.

It seems the module mis_builder in runboat is not updated, therefore the missing fields as @douglascstd said still not there. 
I tried this on my local with the updated mis_builder and the missing fields are shown. 

I have comments about this migration as following:

1. If we use MIS Account Analytic Line as Move Lines Source, then the value in Filter box search view is missing:
<img width="694" alt="Screen Shot 2024-08-15 at 16 04 03" src="https://github.com/user-attachments/assets/a4bdac64-8fcd-485d-b15e-a83942bf045a">

Any plan to update that record so the user can filter the using analytic line in the report view ?

2. Since v16 the analytic line is not easily grab from account.move.line, therefore it's time to support this module so we can make make dynamic report base on the account_analytic. I suggest to use analytic_account as basis of KPI expression. So whenever user put kpi, example: bale[], therefore it will refer to analytic_account not account. Then, the Auto Expand also can be refer to analytic_account as well. I'm hoping this feature can be adopted in the core of MIS Builder, if not, having this here will be okay as well.

2025-01-08 08:43 UTC, sbidoul commented
/ocabot migration mis_builder_analytic

2025-01-08 08:47 UTC, sbidoul approved these changes
Code looks good to me. Compared with v14.

@hitrosol regarding your remarks:

1. (missing search view on the `mis.account.analytic.line` model) this would be a nice addition, but not blocking for the migration, IMO.
2. (use analytic_account as basis of KPI expression) that would be another module with a different view. I think this has been attempted in previous versions.

2025-01-08 09:11 UTC, vdewulf commented
Hello @peluko00, thanks for migrating this module in v16. 
I was looking for a way to create a MIS report with accounting lines and analytic account lines in order to control the split of costs/revenues on various subventions and projects for my customers (for my second job as an accountant). This module matches perfectly our needs.

Here is my functional review based on tests with runboat (thanks @sbidoul for making it possible today).

1. I created a customer invoice with 2 analytic accounts on one accounting line, splitting the revenues into 20% and 80%.
![Sélection_296](https://github.com/user-attachments/assets/dea2a89b-ba3b-46e8-81d1-6463204a07e4)

2. The corresponding analytic items are shown like this:
![Sélection_297](https://github.com/user-attachments/assets/55ebd9e3-0040-4f56-8373-cedebd805f96)

3. I created a report in MIS Report menu, using a basic template (test, that only show the balance of the account 40000). I activated the comparison mode and added 3 columns: 1 with the source from accounting lines, 1 with the alternative sources from analytic lines with the filter on analytic account "Asustek" and the last with the alternative sources from analytic lines with the filter on analytic account "CamptoCamp":
![Sélection_298](https://github.com/user-attachments/assets/5266f88b-d04e-4b8b-9b39-f7225b479135)
Details on the config:
![Sélection_299](https://github.com/user-attachments/assets/11bbdfca-b46b-49a3-bef5-7de424f88254)

4. Result of the report shows the values from the analytic lines.
![Sélection_300](https://github.com/user-attachments/assets/9bef7845-c192-4880-824e-1679f8913092)

5. In a further step I can then easily compare the total on the account 40000 and the total of each analytic account, and make sure there is no dubble assignation of the same invoice on different analytic accounts (important in the context of reporting to subventions bodies for example) or that I didn't miss the encoding of an analytic account on an invoice.
![Sélection_301](https://github.com/user-attachments/assets/b3b23337-5352-4853-bcde-8f80f068801c)

This is working as I expect it. I didn't check the widgets options and other filters though.

2025-01-08 09:13 UTC, sbidoul commented
/ocabot merge nobump

2025-01-08 09:17 UTC, merged